### ISSUE TITLE
Python 101

### ISSUE THREAD

**Issue by CookieLover** [CookieLover/TeachingEventRepo#5]
Yun Zhe and Alimi

**Comment by CookieLover** [comment]
Alimi and Yun Zhe

**Comment by muhammadadrian** [comment]
@CookieLover Python 101 please update

**Comment by CookieLover** [comment]
Introduction / Short talk:
- What is Python?
- Advantages of Python
- How I learned Python
	- Found 10 hour online course
	- All free
- Talk about debugging
- Duration 10 - 15 minutes

Learning:
- Teach basics of Python
- Students will code using online Python compiler. https://www.onlinegdb.com/online_python_compiler
- Variables, list, loops and if’s

Quiz:
- MCC style quiz. Website that explains a problem and has an input. 
Participants put answer and are told if they are right or wrong
- Questions undecided. (I’m going to talk with Yun Zhe to figure what questions we want to ask them)
- Some question ideas;
 	- Make Fibonnaci
	- Calculate sum of list without sum function

To do list:
- Create slides for Introduction
- Create question website
- Discuss questions with Yun Zhe

**Comment by muhammadadrian** [comment]
Awesome! I especially like the online Python compiler bit! 
And the Quiz! Will that be on Google docs?

**Comment by CookieLover** [comment]
I'm planning to make a website for the quizzes. Nothing too fancy though
