### ISSUE TITLE
Arduino and Rasberry Pie

### ISSUE THREAD

**Issue by CookieLover** [CookieLover/TeachingEventRepo#6]
Xuan

**Comment by LAFARGAMER** [comment]
**Talk about what is Arduino**
- https://docs.google.com/document/d/16VRPbGQDhHJUurdzjSGEIjejYNc9SFVUOeHvF6m0G7s/edit?usp=sharing

**Then straight to hands-on! (required a laptop)**
- Setup Arduino Web Editor
- Talk them through the interface of the editor
- Have them create a few simple codes _(step-by-step)_
- Then give them a simple challenge that they have to complete through what they have previously learned within a time frame _(depending on how much time I have left)_

Summarise Arduino in a very short way, talk a little more about Raspberry pi and what you can do with it.
END

More detailed update to be made
