### ISSUE TITLE
Machine Learning

### ISSUE THREAD

**Issue by CookieLover** [CookieLover/TeachingEventRepo#7]
**Talk about what is machine learning**
What is Machine Learning?
https://docs.google.com/presentation/d/1XFv7ckz3WeGz8uKqypkVGnZlESw-Yy9DKSqN0B5wL4E/edit?usp=sharing

Talk about an algorithm, kNN (K-Nearest Neighbours).

**Activities:**
- Walk them through the algorithm kNN
- Steps:

    - Step 0: Pick a value of k, (try different values)
    - Step 1: Compute distances between query and observations in data set.
    - Step 2: Rank observations in data set by distance
    - Step 3: Keep only k observations with shortest distances
    - Step 4: Count the amount of observations with outcomes 0 and 1
    - Step 5: Select the most common outcome for prediction

**To do:**
~- Find a good date set containing only simple numbers i.e no decimals~
- Randomly generated dataset will be used.

**Comment by CookieLover** [comment]
Yun Zhe and Alimi

**Comment by muhammadadrian** [comment]
@REDNETCoder @CookieLover Outline and please decide on a dataset. 26th is merely days away

**Comment by Praharsh1109** [comment]
algorithm for the machine learning:
step 0: Pick a value of k, (try different values)
Step 1: Compute distances between queries and observations in the data set.
Step 2: Rank observations in data set by distance
Step 3: Keep only k observations with shortest distances
Step 4: Count the number of observations with outcomes 0 and 1
Step 5: Select the most common outcome for prediction

**Comment by hooyunzhe** [comment]
> algorithm for the machine learning:
> step 0: Pick a value of k, (try different values)
> Step 1: Compute distances between queries and observations in the data set.
> Step 2: Rank observations in data set by distance
> Step 3: Keep only k observations with shortest distances
> Step 4: Count the number of observations with outcomes 0 and 1
> Step 5: Select the most common outcome for prediction

Why are you repeating what I typed??
